version: '3.5'

name: livriq
services:
  db:
    image: postgres
    container_name: livriq-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: livriq
      POSTGRES_PASSWORD: root
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - livriq-network
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: livriq-app
    restart: unless-stopped
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/app
      # - /app/node_modules
    depends_on:
      - db
    networks:
      - livriq-network


volumes:
  dbdata:

networks:
  livriq-network:
    driver: bridge


    
